return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.10.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 20,
  height = 28,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 11,
  nextobjectid = 60,
  parallaxorigin = {
    x = -320,
    y = -240
  },
  properties = {
    ["border"] = "church_b",
    ["music"] = "second_church",
    ["name"] = "Second Sanctuary"
  },
  tilesets = {
    {
      name = "bg_dw_church_tileset_new",
      firstgid = 1,
      filename = "../../../tilesets/bg_dw_church_tileset_new.tsx"
    },
    {
      name = "bg_dw_church_2_tileset",
      firstgid = 583,
      filename = "../../../tilesets/bg_dw_church_2_tileset.tsx"
    },
    {
      name = "church_objects",
      firstgid = 781,
      filename = "../../../tilesets/church_objects.tsx",
      exportfilename = "../../../tilesets/church_objects.lua"
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "objects_parallax2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 0.6,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = -280,
          y = 240,
          width = 640,
          height = 200,
          rotation = 0,
          gid = 793,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 240,
          width = 640,
          height = 200,
          rotation = 0,
          gid = 793,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = -280,
          y = 760,
          width = 640,
          height = 200,
          rotation = 0,
          gid = 793,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 760,
          width = 640,
          height = 200,
          rotation = 0,
          gid = 793,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects_parallax",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 0.7,
      parallaxy = 0.7,
      properties = {},
      objects = {
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 1160,
          width = 640,
          height = 1600,
          rotation = 330,
          gid = 785,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "objects_shadow",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 1120,
          width = 900,
          height = 800,
          rotation = 270,
          gid = 789,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "objects_osc",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 41,
          name = "tile_oscillate",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 120,
          width = 320,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "texturescroller",
          type = "",
          shape = "point",
          x = -32,
          y = -186,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["type"] = "hsv"
          }
        },
        {
          id = 54,
          name = "tile_oscillate",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 240,
          width = 240,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "tile_oscillate",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 360,
          width = 240,
          height = 720,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "tile_oscillate",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 960,
          width = 440,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 28,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 80, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 80, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 80, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 80, 752, 751, 770, 599, 599, 769, 593, 669, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 770, 599, 599, 760, 778, 761, 599, 769, 678, 669, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 610, 610, 610, 610, 610, 610, 610, 610, 687, 678, 669, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 696, 687, 678, 616, 617, 618, 80, 80, 80, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 696, 687, 625, 626, 627, 80, 80, 80, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 696, 634, 635, 636, 80, 80, 80, 0,
        0, 0, 0, 80, 80, 80, 599, 769, 593, 0, 0, 0, 0, 80, 80, 80, 584, 585, 586, 0,
        0, 0, 0, 80, 80, 80, 761, 599, 769, 0, 0, 0, 0, 80, 80, 80, 593, 594, 595, 0,
        0, 0, 0, 80, 584, 585, 586, 80, 80, 0, 0, 0, 0, 80, 80, 80, 80, 80, 599, 0,
        0, 0, 0, 80, 593, 594, 595, 80, 80, 0, 0, 0, 670, 80, 80, 80, 752, 751, 770, 0,
        0, 0, 0, 80, 80, 80, 80, 80, 80, 0, 0, 670, 679, 80, 80, 770, 599, 599, 760, 0,
        0, 0, 0, 80, 80, 80, 80, 80, 80, 0, 670, 679, 688, 610, 610, 610, 610, 610, 610, 0,
        0, 0, 0, 80, 80, 80, 584, 585, 586, 670, 679, 688, 697, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 80, 80, 80, 593, 594, 595, 679, 688, 697, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 80, 80, 80, 80, 80, 80, 688, 697, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 80, 714, 715, 587, 717, 80, 697, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 80, 723, 724, 725, 726, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 80, 732, 733, 734, 735, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 80, 741, 742, 743, 597, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 80, 588, 80, 80, 80, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 80, 80, 80, 80, 80, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 80, 80, 616, 617, 618, 80, 80, 80, 80, 80, 80, 80, 80, 599, 599, 769, 593,
        0, 0, 0, 80, 80, 625, 626, 627, 80, 80, 599, 599, 769, 593, 80, 80, 778, 761, 599, 769,
        0, 0, 0, 80, 80, 634, 635, 636, 80, 80, 778, 761, 599, 769, 80, 80, 80, 80, 80, 80,
        0, 0, 0, 610, 610, 610, 610, 610, 610, 610, 610, 610, 610, 610, 610, 610, 610, 610, 610, 610
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 0,
          width = 40,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 0,
          width = 240,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 200,
          width = 240,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 240,
          width = 40,
          height = 360,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 560,
          width = 240,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 200,
          width = 280,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 360,
          width = 40,
          height = 760,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 1080,
          width = 680,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 760,
          width = 440,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 360,
          width = 160,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "polygon",
          x = 520,
          y = 480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -160, y = 160 },
            { x = -160, y = 0 }
          },
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "polygon",
          x = 360,
          y = 720,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 160, y = -160 },
            { x = 160, y = 40 },
            { x = 0, y = 40 }
          },
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "polygon",
          x = 360,
          y = 200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 40, y = 0 },
            { x = 160, y = 120 },
            { x = 160, y = 160 },
            { x = 40, y = 40 },
            { x = 0, y = 40 }
          },
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "polygon",
          x = 400,
          y = 120,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 120, y = 120 },
            { x = 120, y = 40 },
            { x = 40, y = -40 },
            { x = 0, y = -40 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 18,
          name = "entry",
          type = "",
          shape = "point",
          x = 120,
          y = 60,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "spawn",
          type = "",
          shape = "point",
          x = 640,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 19,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 80,
          y = -40,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "secsanctuary/ripplepost",
            ["marker"] = "entry"
          }
        },
        {
          id = 38,
          name = "window_glow",
          type = "",
          shape = "point",
          x = 640,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "window_glow",
          type = "",
          shape = "point",
          x = 560,
          y = 880,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "enemy",
          type = "",
          shape = "point",
          x = 200,
          y = 800,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "winglade",
            ["chase"] = "true",
            ["encounter"] = "winglade"
          }
        },
        {
          id = 59,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (You find yourself in a familiar sanctuary...)",
            ["text2"] = "* (You're filled with the power of liminal nostalgia.)"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "objects_overlay",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 22,
          name = "churchfog",
          type = "",
          shape = "point",
          x = -63.561,
          y = 34.1364,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "filter",
          type = "",
          shape = "point",
          x = -117.5,
          y = -69.5,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["type"] = "hsv"
          }
        }
      }
    }
  }
}
